frr version 8.4.4
frr defaults traditional
hostname router-a
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp 65000
 bgp router-id 192.0.2.10
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 neighbor 10.0.0.20 remote-as 65001
 neighbor 10.0.0.21 remote-as 65001
 neighbor 10.0.0.22 remote-as 65001
 neighbor 10.0.0.23 remote-as 65001
 !
 address-family ipv4 unicast
  maximum-paths 1
 exit-address-family
exit
!
end

